# Generated by Django 4.2.2 on 2023-06-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='national_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
