# Generated by Django 4.2.2 on 2023-06-25 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_teacher_national_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='national_no',
            new_name='national_id',
        ),
    ]
