# Generated by Django 4.2.2 on 2023-06-25 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_national_no_teacher_national_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='languages',
        ),
    ]
