# Generated by Django 4.2.2 on 2023-06-29 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_result_grade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
