# Generated by Django 4.2.2 on 2023-06-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_parent_user_parent_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='alternative_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
