# Generated by Django 4.2.2 on 2023-07-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubject',
            name='marks',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
