# Generated by Django 4.2.2 on 2023-06-26 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='class_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='users.classname'),
        ),
    ]
