# Generated by Django 4.2.2 on 2023-06-26 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_stream_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='users.stream'),
        ),
    ]
